#
# Copyright (C) 2016 Marvell International Ltd.
#
# SPDX-License-Identifier:	GPL-2.0
# https://spdx.org/licenses

obj-$(CONFIG_CMD_NETTEST) += \
	netdiag.o \
	nettest.o \
	ncsi.o \
	pktgen.o \
	checksum.o \
	vlan.o \
	m_filter.o \
	mdio.o \
	mac.o \
	phy.o \
	syscon.o \
	cmd_nettest.o \
	objs_ast2700.o
